services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # your multi-stage Next.js Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: tabular-review-frontend
    env_file:
      - .env.frontend
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    external: false
